
plugin:
  name: Ⓜ️ Microgram
  description: crocwork.telegram::lang.plugin.description
  author: crocwork.telegram::lang.plugin.author
  icon: icon-play-circle
  homepage: https://github.com/crocwork/telegram-plugin
