
plugin:
  name: croqo.telegram::lang.plugin.name
  description: croqo.telegram::lang.plugin.description
  author: croqo.telegram::lang.plugin.author
  icon: icon-play-circle
  homepage: https://github.com/croqo/oc-telegram-plugin
