# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Update

# Model Form Field configuration
form: $/crocwork/telegram/models/update/fields.yaml

# Model Class name
modelClass: Crocwork\Telegram\Models\Update

# Default redirect location
defaultRedirect: crocwork/telegram/updates

# Create page
create:
    title: backend::lang.form.create_title
    redirect: crocwork/telegram/updates/update/:id
    redirectClose: crocwork/telegram/updates

# Update page
update:
    title: backend::lang.form.update_title
    redirect: crocwork/telegram/updates
    redirectClose: crocwork/telegram/updates

# Preview page
preview:
    title: backend::lang.form.preview_title
