# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: croqo.telegram::lang.bot.is

# Model Form Field configuration
form: $/croqo/telegram/models/bot/fields.yaml

# Model Class name
modelClass: Croqo\Telegram\Models\Bot

# Default redirect location
defaultRedirect: croqo/telegram/bots

# Create page
create:
    title: backend::lang.form.create_title
    redirect: croqo/telegram/bots/update/:id
    redirectClose: croqo/telegram/bots

# Update page
update:
    title: backend::lang.form.update_title
    redirect: croqo/telegram/bots
    redirectClose: croqo/telegram/bots

# Preview page
preview:
    title: backend::lang.form.preview_title
