# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: crocwork.telegram::lang.bot.is

# Model Form Field configuration
form: $/crocwork/telegram/models/bot/fields.yaml

# Model Class name
modelClass: Crocwork\Telegram\Models\Bot

# Default redirect location
defaultRedirect: crocwork/telegram/bots

# Create page
create:
    title: backend::lang.form.create_title
    redirect: crocwork/telegram/bots/update/:id
    redirectClose: crocwork/telegram/bots

# Update page
update:
    title: backend::lang.form.update_title
    redirect: crocwork/telegram/bots
    redirectClose: crocwork/telegram/bots

# Preview page
preview:
    title: backend::lang.form.preview_title
